### ISSUE TITLE
Two small recommendations

### ISSUE THREAD

**Issue by jimpil** [schmee/java-http-clj#2]
Hi there, 

First of all, many thanks for spending the time to wrap the recently incubated java http-client :). 
Secondly, I have two (minor) suggestions to make:

1. Define the Clojure dependency with `:scope "provided"` in your project.clj (this is a library after all - the project depending on it will have Clojure already on the classpath). Additionally, I guess you may want to bump it to 1.10.1 (as opposed to some beta). 
2. Type-hint any boundary functions that return Java objects (e.g. `send-async` return value is a good candidate).

I think these are fairly trivial - hence no PR. Let me know if you would prefer a PR though... 

Thanks again! ;)

**Comment by schmee** [comment]
Hi @jimpil, you're very welcome, and thanks for the feedback!

I've just pushed 206b32505ca0bb1bedcd981cd728cd71f0ddd72e and 1a18a5f154cd13775820ecc8c72cb5c4a4f581d6, would you mind taking a look and see if they address your issues? Let me know if I missed some function, haven't been around in Clojure land for a while 😉

**Comment by jimpil** [comment]
Yeah nice job - that's exactly what I had in mind ;)  Thanks a million!

**Comment by schmee** [comment]
@jimpil Released 0.4.1! https://clojars.org/java-http-clj
