### ISSUE TITLE
Specs for callback should be `ifn?` rather than `fn?`

### ISSUE THREAD

**Issue by jjttjj** [schmee/java-http-clj#5]
Hi, nice library!
It's a small thing but I believe the cases where you use `fn?` in the websocket and http client should be `ifn?` instead.
Specifically I'm using the missionary library which seems to internally use constructs as callbacks which implement `IFn` but are not `Fn`s. This works fine but fails the spec check if I turn on instrumentation.
It seems to me like the specs should be ok with anything `invoke`able, ie anything that satisfies `ifn?`. 
I can provide a PR on request.

**Comment by schmee** [comment]
Hi @jjttjj, thanks for the kind words!

You are correct, I'll make a PR and a small release to fix this in the coming week 👍

**Comment by schmee** [comment]
@jjttjj this is fixed in 0.4.2 which is released on Clojars. Sorry for taking so long to fix this! 🙏
